# @see https://github.com/PiotrPress/github-composer/blob/master/.github/workflows/update.yml
name: Rebuild packagist
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event--fine-grained-access-tokens
      # Requires Actions (write) permission
      - name: Trigger rebuild
        run: |
          curl -L --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -d '{"ref":"master","inputs":{}}' \
            https://api.github.com/repos/generoi/packagist/actions/workflows/satis.yml/dispatches
