name: Rebuild packagist
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild
        run: |
          curl -L --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            https://api.github.com/repos/generoi/packagist/actions/workflows/satis/dispatches
