# @see https://github.com/PiotrPress/github-composer/blob/master/.github/workflows/update.yml
name: Rebuild packagist
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Requires Contents (write) permission
      - name: Trigger rebuild
        run: |
          curl -L --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token }}" \
            -d '{"event_type":"Satis rebuild","client_payload":{"repository":"${{ github.repository }}"}}' \
            https://api.github.com/repos/generoi/packagist/dispatches
